ERROR - 2024-12-20 06:08:54 --> ErrorException: pg_query(): Query failed: ERROR:  column &quot;created_at&quot; of relation &quot;student_profiles&quot; does not exist
LINE 1: ...files&quot; (&quot;student_id&quot;, &quot;name&quot;, &quot;email&quot;, &quot;address&quot;, &quot;created_a...
                                                             ^ in C:\laragon\www\UPSI_SkillHub\system\Database\Postgre\Connection.php:204
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\laragon\\www\\...', 204)
#1 C:\laragon\www\UPSI_SkillHub\system\Database\Postgre\Connection.php(204): pg_query(Object(PgSql\Connection), 'INSERT INTO "st...')
#2 C:\laragon\www\UPSI_SkillHub\system\Database\BaseConnection.php(734): CodeIgniter\Database\Postgre\Connection->execute('INSERT INTO "st...')
#3 C:\laragon\www\UPSI_SkillHub\system\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO "st...')
#4 C:\laragon\www\UPSI_SkillHub\system\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO "st...', Array, false)
#5 C:\laragon\www\UPSI_SkillHub\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#6 C:\laragon\www\UPSI_SkillHub\system\BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#7 C:\laragon\www\UPSI_SkillHub\system\Model.php(802): CodeIgniter\BaseModel->insert(Array, true)
#8 C:\laragon\www\UPSI_SkillHub\app\Controllers\AuthController.php(113): CodeIgniter\Model->insert(Array)
#9 C:\laragon\www\UPSI_SkillHub\system\CodeIgniter.php(933): App\Controllers\AuthController->store()
#10 C:\laragon\www\UPSI_SkillHub\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
#11 C:\laragon\www\UPSI_SkillHub\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\laragon\www\UPSI_SkillHub\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#13 C:\laragon\www\UPSI_SkillHub\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 C:\laragon\www\UPSI_SkillHub\public\index.php(46): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 C:\laragon\www\UPSI_SkillHub\system\rewrite.php(44): require_once('C:\\laragon\\www\\...')
#16 {main}
ERROR - 2024-12-20 06:09:00 --> ErrorException: pg_query(): Query failed: ERROR:  column &quot;created_at&quot; of relation &quot;student_profiles&quot; does not exist
LINE 1: INSERT INTO &quot;student_profiles&quot; (&quot;student_id&quot;, &quot;created_at&quot;, ...
                                                      ^ in C:\laragon\www\UPSI_SkillHub\system\Database\Postgre\Connection.php:204
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\laragon\\www\\...', 204)
#1 C:\laragon\www\UPSI_SkillHub\system\Database\Postgre\Connection.php(204): pg_query(Object(PgSql\Connection), 'INSERT INTO "st...')
#2 C:\laragon\www\UPSI_SkillHub\system\Database\BaseConnection.php(734): CodeIgniter\Database\Postgre\Connection->execute('INSERT INTO "st...')
#3 C:\laragon\www\UPSI_SkillHub\system\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO "st...')
#4 C:\laragon\www\UPSI_SkillHub\system\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO "st...', Array, false)
#5 C:\laragon\www\UPSI_SkillHub\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#6 C:\laragon\www\UPSI_SkillHub\system\BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#7 C:\laragon\www\UPSI_SkillHub\system\Model.php(802): CodeIgniter\BaseModel->insert(Array, true)
#8 C:\laragon\www\UPSI_SkillHub\app\Controllers\StudentProfileController.php(42): CodeIgniter\Model->insert(Array)
#9 C:\laragon\www\UPSI_SkillHub\system\CodeIgniter.php(933): App\Controllers\StudentProfileController->edit('D20211097850')
#10 C:\laragon\www\UPSI_SkillHub\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\StudentProfileController))
#11 C:\laragon\www\UPSI_SkillHub\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\laragon\www\UPSI_SkillHub\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#13 C:\laragon\www\UPSI_SkillHub\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 C:\laragon\www\UPSI_SkillHub\public\index.php(46): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 C:\laragon\www\UPSI_SkillHub\system\rewrite.php(44): require_once('C:\\laragon\\www\\...')
#16 {main}
ERROR - 2024-12-20 06:09:29 --> ErrorException: pg_query(): Query failed: ERROR:  column &quot;updated_at&quot; of relation &quot;student_profiles&quot; does not exist
LINE 1: ... &quot;city&quot; = NULL, &quot;state&quot; = NULL, &quot;country&quot; = NULL, &quot;updated_a...
                                                             ^ in C:\laragon\www\UPSI_SkillHub\system\Database\Postgre\Connection.php:204
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\laragon\\www\\...', 204)
#1 C:\laragon\www\UPSI_SkillHub\system\Database\Postgre\Connection.php(204): pg_query(Object(PgSql\Connection), 'UPDATE "student...')
#2 C:\laragon\www\UPSI_SkillHub\system\Database\BaseConnection.php(734): CodeIgniter\Database\Postgre\Connection->execute('UPDATE "student...')
#3 C:\laragon\www\UPSI_SkillHub\system\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE "student...')
#4 C:\laragon\www\UPSI_SkillHub\system\Database\BaseBuilder.php(2516): CodeIgniter\Database\BaseConnection->query('UPDATE "student...', Array, false)
#5 C:\laragon\www\UPSI_SkillHub\system\Model.php(461): CodeIgniter\Database\BaseBuilder->update()
#6 C:\laragon\www\UPSI_SkillHub\system\BaseModel.php(1028): CodeIgniter\Model->doUpdate(NULL, Array)
#7 C:\laragon\www\UPSI_SkillHub\system\Model.php(865): CodeIgniter\BaseModel->update(NULL, Array)
#8 C:\laragon\www\UPSI_SkillHub\app\Controllers\StudentProfileController.php(79): CodeIgniter\Model->update()
#9 C:\laragon\www\UPSI_SkillHub\system\CodeIgniter.php(933): App\Controllers\StudentProfileController->update()
#10 C:\laragon\www\UPSI_SkillHub\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\StudentProfileController))
#11 C:\laragon\www\UPSI_SkillHub\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\laragon\www\UPSI_SkillHub\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#13 C:\laragon\www\UPSI_SkillHub\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 C:\laragon\www\UPSI_SkillHub\public\index.php(46): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 C:\laragon\www\UPSI_SkillHub\system\rewrite.php(44): require_once('C:\\laragon\\www\\...')
#16 {main}
ERROR - 2024-12-20 06:09:29 --> ErrorException: pg_query(): Query failed: ERROR:  column &quot;created_at&quot; of relation &quot;student_profiles&quot; does not exist
LINE 1: INSERT INTO &quot;student_profiles&quot; (&quot;student_id&quot;, &quot;created_at&quot;, ...
                                                      ^ in C:\laragon\www\UPSI_SkillHub\system\Database\Postgre\Connection.php:204
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\laragon\\www\\...', 204)
#1 C:\laragon\www\UPSI_SkillHub\system\Database\Postgre\Connection.php(204): pg_query(Object(PgSql\Connection), 'INSERT INTO "st...')
#2 C:\laragon\www\UPSI_SkillHub\system\Database\BaseConnection.php(734): CodeIgniter\Database\Postgre\Connection->execute('INSERT INTO "st...')
#3 C:\laragon\www\UPSI_SkillHub\system\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO "st...')
#4 C:\laragon\www\UPSI_SkillHub\system\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO "st...', Array, false)
#5 C:\laragon\www\UPSI_SkillHub\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#6 C:\laragon\www\UPSI_SkillHub\system\BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#7 C:\laragon\www\UPSI_SkillHub\system\Model.php(802): CodeIgniter\BaseModel->insert(Array, true)
#8 C:\laragon\www\UPSI_SkillHub\app\Controllers\StudentProfileController.php(42): CodeIgniter\Model->insert(Array)
#9 C:\laragon\www\UPSI_SkillHub\system\CodeIgniter.php(933): App\Controllers\StudentProfileController->edit('D20211097850')
#10 C:\laragon\www\UPSI_SkillHub\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\StudentProfileController))
#11 C:\laragon\www\UPSI_SkillHub\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\laragon\www\UPSI_SkillHub\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#13 C:\laragon\www\UPSI_SkillHub\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 C:\laragon\www\UPSI_SkillHub\public\index.php(46): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 C:\laragon\www\UPSI_SkillHub\system\rewrite.php(44): require_once('C:\\laragon\\www\\...')
#16 {main}
ERROR - 2024-12-20 06:55:28 --> ErrorException: pg_query(): Query failed: ERROR:  column &quot;created_at&quot; of relation &quot;student_profiles&quot; does not exist
LINE 1: INSERT INTO &quot;student_profiles&quot; (&quot;student_id&quot;, &quot;created_at&quot;, ...
                                                      ^ in C:\laragon\www\UPSI_SkillHub\system\Database\Postgre\Connection.php:204
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\laragon\\www\\...', 204)
#1 C:\laragon\www\UPSI_SkillHub\system\Database\Postgre\Connection.php(204): pg_query(Object(PgSql\Connection), 'INSERT INTO "st...')
#2 C:\laragon\www\UPSI_SkillHub\system\Database\BaseConnection.php(734): CodeIgniter\Database\Postgre\Connection->execute('INSERT INTO "st...')
#3 C:\laragon\www\UPSI_SkillHub\system\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO "st...')
#4 C:\laragon\www\UPSI_SkillHub\system\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO "st...', Array, false)
#5 C:\laragon\www\UPSI_SkillHub\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#6 C:\laragon\www\UPSI_SkillHub\system\BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#7 C:\laragon\www\UPSI_SkillHub\system\Model.php(802): CodeIgniter\BaseModel->insert(Array, true)
#8 C:\laragon\www\UPSI_SkillHub\app\Controllers\StudentProfileController.php(42): CodeIgniter\Model->insert(Array)
#9 C:\laragon\www\UPSI_SkillHub\system\CodeIgniter.php(933): App\Controllers\StudentProfileController->edit('D20211097850')
#10 C:\laragon\www\UPSI_SkillHub\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\StudentProfileController))
#11 C:\laragon\www\UPSI_SkillHub\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\laragon\www\UPSI_SkillHub\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#13 C:\laragon\www\UPSI_SkillHub\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 C:\laragon\www\UPSI_SkillHub\public\index.php(46): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 C:\laragon\www\UPSI_SkillHub\system\rewrite.php(44): require_once('C:\\laragon\\www\\...')
#16 {main}
CRITICAL - 2024-12-20 06:55:38 --> CodeIgniter\Filters\Exceptions\FilterException: "auth" filter must have a matching alias defined.
[Method: GET, Route: dashboard]
in SYSTEMPATH\Filters\Filters.php on line 495.
 1 SYSTEMPATH\Filters\Filters.php(495): CodeIgniter\Filters\Exceptions\FilterException::forNoAlias('auth')
 2 SYSTEMPATH\Filters\Filters.php(547): CodeIgniter\Filters\Filters->enableFilter('auth', 'before')
 3 SYSTEMPATH\CodeIgniter.php(469): CodeIgniter\Filters\Filters->enableFilters([...], 'before')
 4 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH\index.php(46): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
 8 SYSTEMPATH\rewrite.php(44): require_once('C:\\laragon\\www\\UPSI_SkillHub\\public\\index.php')
CRITICAL - 2024-12-20 07:00:16 --> CodeIgniter\Filters\Exceptions\FilterException: "auth" filter must have a matching alias defined.
[Method: GET, Route: dashboard]
in SYSTEMPATH\Filters\Filters.php on line 495.
 1 SYSTEMPATH\Filters\Filters.php(495): CodeIgniter\Filters\Exceptions\FilterException::forNoAlias('auth')
 2 SYSTEMPATH\Filters\Filters.php(547): CodeIgniter\Filters\Filters->enableFilter('auth', 'before')
 3 SYSTEMPATH\CodeIgniter.php(469): CodeIgniter\Filters\Filters->enableFilters([...], 'before')
 4 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH\index.php(46): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
 8 SYSTEMPATH\rewrite.php(44): require_once('C:\\laragon\\www\\UPSI_SkillHub\\public\\index.php')
ERROR - 2024-12-20 07:02:29 --> ErrorException: pg_query(): Query failed: ERROR:  column &quot;created_at&quot; of relation &quot;student_profiles&quot; does not exist
LINE 1: INSERT INTO &quot;student_profiles&quot; (&quot;student_id&quot;, &quot;created_at&quot;, ...
                                                      ^ in C:\laragon\www\UPSI_SkillHub\system\Database\Postgre\Connection.php:204
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\laragon\\www\\...', 204)
#1 C:\laragon\www\UPSI_SkillHub\system\Database\Postgre\Connection.php(204): pg_query(Object(PgSql\Connection), 'INSERT INTO "st...')
#2 C:\laragon\www\UPSI_SkillHub\system\Database\BaseConnection.php(734): CodeIgniter\Database\Postgre\Connection->execute('INSERT INTO "st...')
#3 C:\laragon\www\UPSI_SkillHub\system\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO "st...')
#4 C:\laragon\www\UPSI_SkillHub\system\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO "st...', Array, false)
#5 C:\laragon\www\UPSI_SkillHub\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#6 C:\laragon\www\UPSI_SkillHub\system\BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#7 C:\laragon\www\UPSI_SkillHub\system\Model.php(802): CodeIgniter\BaseModel->insert(Array, true)
#8 C:\laragon\www\UPSI_SkillHub\app\Controllers\AuthController.php(85): CodeIgniter\Model->insert(Array)
#9 C:\laragon\www\UPSI_SkillHub\system\CodeIgniter.php(933): App\Controllers\AuthController->store()
#10 C:\laragon\www\UPSI_SkillHub\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
#11 C:\laragon\www\UPSI_SkillHub\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\laragon\www\UPSI_SkillHub\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#13 C:\laragon\www\UPSI_SkillHub\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 C:\laragon\www\UPSI_SkillHub\public\index.php(46): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 C:\laragon\www\UPSI_SkillHub\system\rewrite.php(44): require_once('C:\\laragon\\www\\...')
#16 {main}
ERROR - 2024-12-20 07:02:44 --> ErrorException: pg_query(): Query failed: ERROR:  column &quot;created_at&quot; of relation &quot;student_profiles&quot; does not exist
LINE 1: INSERT INTO &quot;student_profiles&quot; (&quot;student_id&quot;, &quot;created_at&quot;, ...
                                                      ^ in C:\laragon\www\UPSI_SkillHub\system\Database\Postgre\Connection.php:204
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\laragon\\www\\...', 204)
#1 C:\laragon\www\UPSI_SkillHub\system\Database\Postgre\Connection.php(204): pg_query(Object(PgSql\Connection), 'INSERT INTO "st...')
#2 C:\laragon\www\UPSI_SkillHub\system\Database\BaseConnection.php(734): CodeIgniter\Database\Postgre\Connection->execute('INSERT INTO "st...')
#3 C:\laragon\www\UPSI_SkillHub\system\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO "st...')
#4 C:\laragon\www\UPSI_SkillHub\system\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO "st...', Array, false)
#5 C:\laragon\www\UPSI_SkillHub\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#6 C:\laragon\www\UPSI_SkillHub\system\BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#7 C:\laragon\www\UPSI_SkillHub\system\Model.php(802): CodeIgniter\BaseModel->insert(Array, true)
#8 C:\laragon\www\UPSI_SkillHub\app\Controllers\AuthController.php(85): CodeIgniter\Model->insert(Array)
#9 C:\laragon\www\UPSI_SkillHub\system\CodeIgniter.php(933): App\Controllers\AuthController->store()
#10 C:\laragon\www\UPSI_SkillHub\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
#11 C:\laragon\www\UPSI_SkillHub\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\laragon\www\UPSI_SkillHub\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#13 C:\laragon\www\UPSI_SkillHub\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 C:\laragon\www\UPSI_SkillHub\public\index.php(46): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 C:\laragon\www\UPSI_SkillHub\system\rewrite.php(44): require_once('C:\\laragon\\www\\...')
#16 {main}
ERROR - 2024-12-20 07:06:02 --> ErrorException: pg_query(): Query failed: ERROR:  duplicate key value violates unique constraint &quot;users_student_id_key&quot;
DETAIL:  Key (student_id)=(D20211097000) already exists. in C:\laragon\www\UPSI_SkillHub\system\Database\Postgre\Connection.php:204
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\laragon\\www\\...', 204)
#1 C:\laragon\www\UPSI_SkillHub\system\Database\Postgre\Connection.php(204): pg_query(Object(PgSql\Connection), 'INSERT INTO "us...')
#2 C:\laragon\www\UPSI_SkillHub\system\Database\BaseConnection.php(734): CodeIgniter\Database\Postgre\Connection->execute('INSERT INTO "us...')
#3 C:\laragon\www\UPSI_SkillHub\system\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO "us...')
#4 C:\laragon\www\UPSI_SkillHub\system\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO "us...', Array, false)
#5 C:\laragon\www\UPSI_SkillHub\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#6 C:\laragon\www\UPSI_SkillHub\system\BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#7 C:\laragon\www\UPSI_SkillHub\system\Model.php(802): CodeIgniter\BaseModel->insert(Array, true)
#8 C:\laragon\www\UPSI_SkillHub\app\Controllers\AuthController.php(80): CodeIgniter\Model->insert(Array)
#9 C:\laragon\www\UPSI_SkillHub\system\CodeIgniter.php(933): App\Controllers\AuthController->store()
#10 C:\laragon\www\UPSI_SkillHub\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
#11 C:\laragon\www\UPSI_SkillHub\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\laragon\www\UPSI_SkillHub\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#13 C:\laragon\www\UPSI_SkillHub\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 C:\laragon\www\UPSI_SkillHub\public\index.php(46): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 C:\laragon\www\UPSI_SkillHub\system\rewrite.php(44): require_once('C:\\laragon\\www\\...')
#16 {main}
ERROR - 2024-12-20 07:11:21 --> ErrorException: pg_query(): Query failed: ERROR:  column &quot;created_at&quot; of relation &quot;student_profiles&quot; does not exist
LINE 1: INSERT INTO &quot;student_profiles&quot; (&quot;student_id&quot;, &quot;created_at&quot;, ...
                                                      ^ in C:\laragon\www\UPSI_SkillHub\system\Database\Postgre\Connection.php:204
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\laragon\\www\\...', 204)
#1 C:\laragon\www\UPSI_SkillHub\system\Database\Postgre\Connection.php(204): pg_query(Object(PgSql\Connection), 'INSERT INTO "st...')
#2 C:\laragon\www\UPSI_SkillHub\system\Database\BaseConnection.php(734): CodeIgniter\Database\Postgre\Connection->execute('INSERT INTO "st...')
#3 C:\laragon\www\UPSI_SkillHub\system\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO "st...')
#4 C:\laragon\www\UPSI_SkillHub\system\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO "st...', Array, false)
#5 C:\laragon\www\UPSI_SkillHub\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#6 C:\laragon\www\UPSI_SkillHub\system\BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#7 C:\laragon\www\UPSI_SkillHub\system\Model.php(802): CodeIgniter\BaseModel->insert(Array, true)
#8 C:\laragon\www\UPSI_SkillHub\app\Controllers\AuthController.php(97): CodeIgniter\Model->insert(Array)
#9 C:\laragon\www\UPSI_SkillHub\system\CodeIgniter.php(933): App\Controllers\AuthController->store()
#10 C:\laragon\www\UPSI_SkillHub\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
#11 C:\laragon\www\UPSI_SkillHub\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\laragon\www\UPSI_SkillHub\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#13 C:\laragon\www\UPSI_SkillHub\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 C:\laragon\www\UPSI_SkillHub\public\index.php(46): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 C:\laragon\www\UPSI_SkillHub\system\rewrite.php(44): require_once('C:\\laragon\\www\\...')
#16 {main}
ERROR - 2024-12-20 07:11:21 --> Student Profile Insert Error: Array
(
    [code] => 
    [message] => ERROR:  column "created_at" of relation "student_profiles" does not exist
LINE 1: INSERT INTO "student_profiles" ("student_id", "created_at", ...
                                                      ^
)

ERROR - 2024-12-20 07:30:31 --> ErrorException: pg_query(): Query failed: ERROR:  column &quot;created_at&quot; of relation &quot;student_profiles&quot; does not exist
LINE 1: INSERT INTO &quot;student_profiles&quot; (&quot;student_id&quot;, &quot;created_at&quot;, ...
                                                      ^ in C:\laragon\www\UPSI_SkillHub\system\Database\Postgre\Connection.php:204
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\laragon\\www\\...', 204)
#1 C:\laragon\www\UPSI_SkillHub\system\Database\Postgre\Connection.php(204): pg_query(Object(PgSql\Connection), 'INSERT INTO "st...')
#2 C:\laragon\www\UPSI_SkillHub\system\Database\BaseConnection.php(734): CodeIgniter\Database\Postgre\Connection->execute('INSERT INTO "st...')
#3 C:\laragon\www\UPSI_SkillHub\system\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO "st...')
#4 C:\laragon\www\UPSI_SkillHub\system\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO "st...', Array, false)
#5 C:\laragon\www\UPSI_SkillHub\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#6 C:\laragon\www\UPSI_SkillHub\system\BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#7 C:\laragon\www\UPSI_SkillHub\system\Model.php(802): CodeIgniter\BaseModel->insert(Array, true)
#8 C:\laragon\www\UPSI_SkillHub\app\Controllers\AuthController.php(85): CodeIgniter\Model->insert(Array)
#9 C:\laragon\www\UPSI_SkillHub\system\CodeIgniter.php(933): App\Controllers\AuthController->store()
#10 C:\laragon\www\UPSI_SkillHub\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
#11 C:\laragon\www\UPSI_SkillHub\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\laragon\www\UPSI_SkillHub\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#13 C:\laragon\www\UPSI_SkillHub\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 C:\laragon\www\UPSI_SkillHub\public\index.php(46): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 C:\laragon\www\UPSI_SkillHub\system\rewrite.php(44): require_once('C:\\laragon\\www\\...')
#16 {main}
ERROR - 2024-12-20 07:47:23 --> ErrorException: pg_query(): Query failed: ERROR:  column &quot;created_at&quot; of relation &quot;student_profiles&quot; does not exist
LINE 1: INSERT INTO &quot;student_profiles&quot; (&quot;student_id&quot;, &quot;created_at&quot;, ...
                                                      ^ in C:\laragon\www\UPSI_SkillHub\system\Database\Postgre\Connection.php:204
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\laragon\\www\\...', 204)
#1 C:\laragon\www\UPSI_SkillHub\system\Database\Postgre\Connection.php(204): pg_query(Object(PgSql\Connection), 'INSERT INTO "st...')
#2 C:\laragon\www\UPSI_SkillHub\system\Database\BaseConnection.php(734): CodeIgniter\Database\Postgre\Connection->execute('INSERT INTO "st...')
#3 C:\laragon\www\UPSI_SkillHub\system\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO "st...')
#4 C:\laragon\www\UPSI_SkillHub\system\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO "st...', Array, false)
#5 C:\laragon\www\UPSI_SkillHub\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#6 C:\laragon\www\UPSI_SkillHub\system\BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#7 C:\laragon\www\UPSI_SkillHub\system\Model.php(802): CodeIgniter\BaseModel->insert(Array, true)
#8 C:\laragon\www\UPSI_SkillHub\app\Controllers\AuthController.php(86): CodeIgniter\Model->insert(Array)
#9 C:\laragon\www\UPSI_SkillHub\system\CodeIgniter.php(933): App\Controllers\AuthController->store()
#10 C:\laragon\www\UPSI_SkillHub\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
#11 C:\laragon\www\UPSI_SkillHub\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\laragon\www\UPSI_SkillHub\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#13 C:\laragon\www\UPSI_SkillHub\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 C:\laragon\www\UPSI_SkillHub\public\index.php(46): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 C:\laragon\www\UPSI_SkillHub\system\rewrite.php(44): require_once('C:\\laragon\\www\\...')
#16 {main}
ERROR - 2024-12-20 07:47:23 --> Student Profile Insert Error: Array
(
    [code] => 
    [message] => ERROR:  column "created_at" of relation "student_profiles" does not exist
LINE 1: INSERT INTO "student_profiles" ("student_id", "created_at", ...
                                                      ^
)

ERROR - 2024-12-20 08:10:43 --> ErrorException: pg_query(): Query failed: ERROR:  column &quot;updated_at&quot; of relation &quot;student_profiles&quot; does not exist
LINE 1: ...O &quot;student_profiles&quot; (&quot;student_id&quot;, &quot;created_at&quot;, &quot;updated_a...
                                                             ^ in C:\laragon\www\UPSI_SkillHub\system\Database\Postgre\Connection.php:204
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\laragon\\www\\...', 204)
#1 C:\laragon\www\UPSI_SkillHub\system\Database\Postgre\Connection.php(204): pg_query(Object(PgSql\Connection), 'INSERT INTO "st...')
#2 C:\laragon\www\UPSI_SkillHub\system\Database\BaseConnection.php(734): CodeIgniter\Database\Postgre\Connection->execute('INSERT INTO "st...')
#3 C:\laragon\www\UPSI_SkillHub\system\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO "st...')
#4 C:\laragon\www\UPSI_SkillHub\system\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO "st...', Array, false)
#5 C:\laragon\www\UPSI_SkillHub\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#6 C:\laragon\www\UPSI_SkillHub\system\BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#7 C:\laragon\www\UPSI_SkillHub\system\Model.php(802): CodeIgniter\BaseModel->insert(Array, true)
#8 C:\laragon\www\UPSI_SkillHub\app\Controllers\AuthController.php(86): CodeIgniter\Model->insert(Array)
#9 C:\laragon\www\UPSI_SkillHub\system\CodeIgniter.php(933): App\Controllers\AuthController->store()
#10 C:\laragon\www\UPSI_SkillHub\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
#11 C:\laragon\www\UPSI_SkillHub\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\laragon\www\UPSI_SkillHub\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#13 C:\laragon\www\UPSI_SkillHub\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 C:\laragon\www\UPSI_SkillHub\public\index.php(46): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 C:\laragon\www\UPSI_SkillHub\system\rewrite.php(44): require_once('C:\\laragon\\www\\...')
#16 {main}
ERROR - 2024-12-20 08:10:43 --> Student Profile Insert Error: Array
(
    [code] => 
    [message] => ERROR:  column "updated_at" of relation "student_profiles" does not exist
LINE 1: ...O "student_profiles" ("student_id", "created_at", "updated_a...
                                                             ^
)

