ERROR - 2025-01-12 04:32:33 --> ErrorException: pg_query(): Query failed: ERROR:  column &quot;updated_at&quot; of relation &quot;users&quot; does not exist
LINE 1: ... &quot;users&quot; (&quot;student_id&quot;, &quot;password&quot;, &quot;created_at&quot;, &quot;updated_a...
                                                             ^ in C:\laragon\www\UPSI_SkillHub\system\Database\Postgre\Connection.php:204
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\laragon\\www\\...', 204)
#1 C:\laragon\www\UPSI_SkillHub\system\Database\Postgre\Connection.php(204): pg_query(Object(PgSql\Connection), 'INSERT INTO "us...')
#2 C:\laragon\www\UPSI_SkillHub\system\Database\BaseConnection.php(734): CodeIgniter\Database\Postgre\Connection->execute('INSERT INTO "us...')
#3 C:\laragon\www\UPSI_SkillHub\system\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO "us...')
#4 C:\laragon\www\UPSI_SkillHub\system\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO "us...', Array, false)
#5 C:\laragon\www\UPSI_SkillHub\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#6 C:\laragon\www\UPSI_SkillHub\system\BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#7 C:\laragon\www\UPSI_SkillHub\system\Model.php(802): CodeIgniter\BaseModel->insert(Array, true)
#8 C:\laragon\www\UPSI_SkillHub\app\Controllers\AuthController.php(80): CodeIgniter\Model->insert(Array)
#9 C:\laragon\www\UPSI_SkillHub\system\CodeIgniter.php(933): App\Controllers\AuthController->store()
#10 C:\laragon\www\UPSI_SkillHub\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
#11 C:\laragon\www\UPSI_SkillHub\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\laragon\www\UPSI_SkillHub\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#13 C:\laragon\www\UPSI_SkillHub\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 C:\laragon\www\UPSI_SkillHub\public\index.php(46): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 C:\laragon\www\UPSI_SkillHub\system\rewrite.php(44): require_once('C:\\laragon\\www\\...')
#16 {main}
CRITICAL - 2025-01-12 15:50:12 --> CodeIgniter\Exceptions\CriticalError: The required PHP extension "pgsql" is not loaded. Install and enable it to use "Postgre" driver.
[Method: POST, Route: register]
in SYSTEMPATH/Database/Database.php on line 182.
 1 SYSTEMPATH/Database/Database.php(59): CodeIgniter\Database\Database->checkDbExtension('Postgre')
 2 SYSTEMPATH/Database/Config.php(84): CodeIgniter\Database\Database->load([...], 'default')
 3 SYSTEMPATH/Model.php(155): CodeIgniter\Database\Config::connect('default')
 4 APPPATH/Controllers/AuthController.php(68): CodeIgniter\Model->__construct()
 5 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\AuthController->store()
 6 SYSTEMPATH/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
 7 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH/Boot.php(325): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH/index.php(46): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-01-12 15:52:45 --> CodeIgniter\Exceptions\CriticalError: The required PHP extension "pgsql" is not loaded. Install and enable it to use "Postgre" driver.
[Method: POST, Route: login]
in SYSTEMPATH/Database/Database.php on line 182.
 1 SYSTEMPATH/Database/Database.php(59): CodeIgniter\Database\Database->checkDbExtension('Postgre')
 2 SYSTEMPATH/Database/Config.php(84): CodeIgniter\Database\Database->load([...], 'default')
 3 SYSTEMPATH/Model.php(155): CodeIgniter\Database\Config::connect('default')
 4 APPPATH/Controllers/AuthController.php(25): CodeIgniter\Model->__construct()
 5 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\AuthController->login()
 6 SYSTEMPATH/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
 7 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH/Boot.php(325): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH/index.php(46): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-01-12 17:25:35 --> Error connecting to the database: ErrorException: pg_connect(): Unable to connect to PostgreSQL server: connection to server at &quot;localhost&quot; (::1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at &quot;localhost&quot; (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections? in /var/www/html/system/Database/Postgre/Connection.php:77
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_connect(): U...', '/var/www/html/s...', 77)
#1 /var/www/html/system/Database/Postgre/Connection.php(77): pg_connect('host=localhost ...')
#2 /var/www/html/system/Database/BaseConnection.php(421): CodeIgniter\Database\Postgre\Connection->connect(false)
#3 /var/www/html/system/Database/BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
#4 /var/www/html/system/Database/BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM "...', Array, false)
#5 /var/www/html/system/Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#6 /var/www/html/system/BaseModel.php(610): CodeIgniter\Model->doFind(true, 'D20211097851')
#7 /var/www/html/app/Controllers/AuthController.php(26): CodeIgniter\BaseModel->find('D20211097851')
#8 /var/www/html/system/CodeIgniter.php(933): App\Controllers\AuthController->login()
#9 /var/www/html/system/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
#10 /var/www/html/system/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 /var/www/html/system/Boot.php(325): CodeIgniter\CodeIgniter->run()
#12 /var/www/html/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 /var/www/html/public/index.php(46): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}
CRITICAL - 2025-01-12 17:25:35 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [Postgre]: pg_connect(): Unable to connect to PostgreSQL server: connection to server at &quot;localhost&quot; (::1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at &quot;localhost&quot; (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
[Method: POST, Route: login]
in SYSTEMPATH/Database/BaseConnection.php on line 467.
 1 SYSTEMPATH/Database/BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH/Database/BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM "users"
WHERE "users"."student_id" = :users.student_id:', [...], false)
 3 SYSTEMPATH/Model.php(210): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH/BaseModel.php(610): CodeIgniter\Model->doFind(true, 'D20211097851')
 5 APPPATH/Controllers/AuthController.php(26): CodeIgniter\BaseModel->find('D20211097851')
 6 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\AuthController->login()
 7 SYSTEMPATH/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
 8 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH/Boot.php(325): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH/index.php(46): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-01-12 17:27:06 --> Error connecting to the database: ErrorException: pg_connect(): Unable to connect to PostgreSQL server: connection to server at &quot;localhost&quot; (::1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at &quot;localhost&quot; (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections? in /var/www/html/system/Database/Postgre/Connection.php:77
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_connect(): U...', '/var/www/html/s...', 77)
#1 /var/www/html/system/Database/Postgre/Connection.php(77): pg_connect('host=localhost ...')
#2 /var/www/html/system/Database/BaseConnection.php(421): CodeIgniter\Database\Postgre\Connection->connect(false)
#3 /var/www/html/system/Database/BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
#4 /var/www/html/system/Database/BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM "...', Array, false)
#5 /var/www/html/system/Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#6 /var/www/html/system/BaseModel.php(610): CodeIgniter\Model->doFind(true, 'D20211097856')
#7 /var/www/html/app/Controllers/AuthController.php(69): CodeIgniter\BaseModel->find('D20211097856')
#8 /var/www/html/system/CodeIgniter.php(933): App\Controllers\AuthController->store()
#9 /var/www/html/system/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
#10 /var/www/html/system/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 /var/www/html/system/Boot.php(325): CodeIgniter\CodeIgniter->run()
#12 /var/www/html/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 /var/www/html/public/index.php(46): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}
CRITICAL - 2025-01-12 17:27:06 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [Postgre]: pg_connect(): Unable to connect to PostgreSQL server: connection to server at &quot;localhost&quot; (::1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at &quot;localhost&quot; (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
[Method: POST, Route: register]
in SYSTEMPATH/Database/BaseConnection.php on line 467.
 1 SYSTEMPATH/Database/BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH/Database/BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM "users"
WHERE "users"."student_id" = :users.student_id:', [...], false)
 3 SYSTEMPATH/Model.php(210): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH/BaseModel.php(610): CodeIgniter\Model->doFind(true, 'D20211097856')
 5 APPPATH/Controllers/AuthController.php(69): CodeIgniter\BaseModel->find('D20211097856')
 6 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\AuthController->store()
 7 SYSTEMPATH/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
 8 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH/Boot.php(325): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH/index.php(46): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-01-12 17:33:31 --> Error connecting to the database: ErrorException: pg_connect(): Unable to connect to PostgreSQL server: connection to server at &quot;localhost&quot; (::1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at &quot;localhost&quot; (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections? in /var/www/html/system/Database/Postgre/Connection.php:77
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_connect(): U...', '/var/www/html/s...', 77)
#1 /var/www/html/system/Database/Postgre/Connection.php(77): pg_connect('host=localhost ...')
#2 /var/www/html/system/Database/BaseConnection.php(421): CodeIgniter\Database\Postgre\Connection->connect(false)
#3 /var/www/html/system/Database/BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
#4 /var/www/html/system/Database/BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM "...', Array, false)
#5 /var/www/html/system/Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#6 /var/www/html/system/BaseModel.php(610): CodeIgniter\Model->doFind(true, 'D20211097856')
#7 /var/www/html/app/Controllers/AuthController.php(69): CodeIgniter\BaseModel->find('D20211097856')
#8 /var/www/html/system/CodeIgniter.php(933): App\Controllers\AuthController->store()
#9 /var/www/html/system/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
#10 /var/www/html/system/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 /var/www/html/system/Boot.php(325): CodeIgniter\CodeIgniter->run()
#12 /var/www/html/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 /var/www/html/public/index.php(46): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}
CRITICAL - 2025-01-12 17:33:31 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [Postgre]: pg_connect(): Unable to connect to PostgreSQL server: connection to server at &quot;localhost&quot; (::1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at &quot;localhost&quot; (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
[Method: POST, Route: register]
in SYSTEMPATH/Database/BaseConnection.php on line 467.
 1 SYSTEMPATH/Database/BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH/Database/BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM "users"
WHERE "users"."student_id" = :users.student_id:', [...], false)
 3 SYSTEMPATH/Model.php(210): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH/BaseModel.php(610): CodeIgniter\Model->doFind(true, 'D20211097856')
 5 APPPATH/Controllers/AuthController.php(69): CodeIgniter\BaseModel->find('D20211097856')
 6 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\AuthController->store()
 7 SYSTEMPATH/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
 8 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH/Boot.php(325): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH/index.php(46): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-01-12 17:38:07 --> Error connecting to the database: ErrorException: pg_connect(): Unable to connect to PostgreSQL server: connection to server at &quot;localhost&quot; (::1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at &quot;localhost&quot; (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections? in /var/www/html/system/Database/Postgre/Connection.php:77
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_connect(): U...', '/var/www/html/s...', 77)
#1 /var/www/html/system/Database/Postgre/Connection.php(77): pg_connect('host=localhost ...')
#2 /var/www/html/system/Database/BaseConnection.php(421): CodeIgniter\Database\Postgre\Connection->connect(false)
#3 /var/www/html/system/Database/BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
#4 /var/www/html/system/Database/BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM "...', Array, false)
#5 /var/www/html/system/Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#6 /var/www/html/system/BaseModel.php(610): CodeIgniter\Model->doFind(true, 'D20211097856')
#7 /var/www/html/app/Controllers/AuthController.php(69): CodeIgniter\BaseModel->find('D20211097856')
#8 /var/www/html/system/CodeIgniter.php(933): App\Controllers\AuthController->store()
#9 /var/www/html/system/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
#10 /var/www/html/system/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 /var/www/html/system/Boot.php(325): CodeIgniter\CodeIgniter->run()
#12 /var/www/html/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 /var/www/html/public/index.php(46): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}
CRITICAL - 2025-01-12 17:38:07 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [Postgre]: pg_connect(): Unable to connect to PostgreSQL server: connection to server at &quot;localhost&quot; (::1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at &quot;localhost&quot; (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
[Method: POST, Route: register]
in SYSTEMPATH/Database/BaseConnection.php on line 467.
 1 SYSTEMPATH/Database/BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH/Database/BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM "users"
WHERE "users"."student_id" = :users.student_id:', [...], false)
 3 SYSTEMPATH/Model.php(210): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH/BaseModel.php(610): CodeIgniter\Model->doFind(true, 'D20211097856')
 5 APPPATH/Controllers/AuthController.php(69): CodeIgniter\BaseModel->find('D20211097856')
 6 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\AuthController->store()
 7 SYSTEMPATH/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
 8 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH/Boot.php(325): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH/index.php(46): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-01-12 17:38:28 --> Error connecting to the database: ErrorException: pg_connect(): Unable to connect to PostgreSQL server: connection to server at &quot;localhost&quot; (::1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at &quot;localhost&quot; (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections? in /var/www/html/system/Database/Postgre/Connection.php:77
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_connect(): U...', '/var/www/html/s...', 77)
#1 /var/www/html/system/Database/Postgre/Connection.php(77): pg_connect('host=localhost ...')
#2 /var/www/html/system/Database/BaseConnection.php(421): CodeIgniter\Database\Postgre\Connection->connect(false)
#3 /var/www/html/system/Database/BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
#4 /var/www/html/system/Database/BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM "...', Array, false)
#5 /var/www/html/system/Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#6 /var/www/html/system/BaseModel.php(610): CodeIgniter\Model->doFind(true, 'D20211097851')
#7 /var/www/html/app/Controllers/AuthController.php(26): CodeIgniter\BaseModel->find('D20211097851')
#8 /var/www/html/system/CodeIgniter.php(933): App\Controllers\AuthController->login()
#9 /var/www/html/system/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
#10 /var/www/html/system/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 /var/www/html/system/Boot.php(325): CodeIgniter\CodeIgniter->run()
#12 /var/www/html/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 /var/www/html/public/index.php(46): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}
CRITICAL - 2025-01-12 17:38:28 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [Postgre]: pg_connect(): Unable to connect to PostgreSQL server: connection to server at &quot;localhost&quot; (::1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at &quot;localhost&quot; (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
[Method: POST, Route: login]
in SYSTEMPATH/Database/BaseConnection.php on line 467.
 1 SYSTEMPATH/Database/BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH/Database/BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM "users"
WHERE "users"."student_id" = :users.student_id:', [...], false)
 3 SYSTEMPATH/Model.php(210): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH/BaseModel.php(610): CodeIgniter\Model->doFind(true, 'D20211097851')
 5 APPPATH/Controllers/AuthController.php(26): CodeIgniter\BaseModel->find('D20211097851')
 6 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\AuthController->login()
 7 SYSTEMPATH/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
 8 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH/Boot.php(325): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH/index.php(46): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-01-12 17:43:21 --> Error connecting to the database: ErrorException: pg_connect(): Unable to connect to PostgreSQL server: connection to server at &quot;localhost&quot; (::1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at &quot;localhost&quot; (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections? in /var/www/html/system/Database/Postgre/Connection.php:77
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_connect(): U...', '/var/www/html/s...', 77)
#1 /var/www/html/system/Database/Postgre/Connection.php(77): pg_connect('host=localhost ...')
#2 /var/www/html/system/Database/BaseConnection.php(421): CodeIgniter\Database\Postgre\Connection->connect(false)
#3 /var/www/html/system/Database/BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
#4 /var/www/html/system/Database/BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM "...', Array, false)
#5 /var/www/html/system/Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#6 /var/www/html/system/BaseModel.php(610): CodeIgniter\Model->doFind(true, 'D20211097851')
#7 /var/www/html/app/Controllers/AuthController.php(26): CodeIgniter\BaseModel->find('D20211097851')
#8 /var/www/html/system/CodeIgniter.php(933): App\Controllers\AuthController->login()
#9 /var/www/html/system/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
#10 /var/www/html/system/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 /var/www/html/system/Boot.php(325): CodeIgniter\CodeIgniter->run()
#12 /var/www/html/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 /var/www/html/public/index.php(46): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}
CRITICAL - 2025-01-12 17:43:21 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [Postgre]: pg_connect(): Unable to connect to PostgreSQL server: connection to server at &quot;localhost&quot; (::1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at &quot;localhost&quot; (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
[Method: POST, Route: login]
in SYSTEMPATH/Database/BaseConnection.php on line 467.
 1 SYSTEMPATH/Database/BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH/Database/BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM "users"
WHERE "users"."student_id" = :users.student_id:', [...], false)
 3 SYSTEMPATH/Model.php(210): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH/BaseModel.php(610): CodeIgniter\Model->doFind(true, 'D20211097851')
 5 APPPATH/Controllers/AuthController.php(26): CodeIgniter\BaseModel->find('D20211097851')
 6 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\AuthController->login()
 7 SYSTEMPATH/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
 8 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH/Boot.php(325): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH/index.php(46): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-01-12 18:03:49 --> ErrorException: pg_query(): Query failed: ERROR:  relation &quot;users&quot; does not exist
LINE 2: FROM &quot;users&quot;
             ^ in /var/www/html/system/Database/Postgre/Connection.php:204
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', '/var/www/html/s...', 204)
#1 /var/www/html/system/Database/Postgre/Connection.php(204): pg_query(Object(PgSql\Connection), 'SELECT *\nFROM "...')
#2 /var/www/html/system/Database/BaseConnection.php(734): CodeIgniter\Database\Postgre\Connection->execute('SELECT *\nFROM "...')
#3 /var/www/html/system/Database/BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM "...')
#4 /var/www/html/system/Database/BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM "...', Array, false)
#5 /var/www/html/system/Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#6 /var/www/html/system/BaseModel.php(610): CodeIgniter\Model->doFind(true, 'D20211097851')
#7 /var/www/html/app/Controllers/AuthController.php(26): CodeIgniter\BaseModel->find('D20211097851')
#8 /var/www/html/system/CodeIgniter.php(933): App\Controllers\AuthController->login()
#9 /var/www/html/system/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
#10 /var/www/html/system/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 /var/www/html/system/Boot.php(325): CodeIgniter\CodeIgniter->run()
#12 /var/www/html/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 /var/www/html/public/index.php(46): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}
CRITICAL - 2025-01-12 18:03:49 --> Error: Call to a member function getFirstRow() on bool
[Method: POST, Route: login]
in SYSTEMPATH/Model.php on line 211.
 1 SYSTEMPATH/BaseModel.php(610): CodeIgniter\Model->doFind(true, 'D20211097851')
 2 APPPATH/Controllers/AuthController.php(26): CodeIgniter\BaseModel->find('D20211097851')
 3 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\AuthController->login()
 4 SYSTEMPATH/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
 5 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 SYSTEMPATH/Boot.php(325): CodeIgniter\CodeIgniter->run()
 7 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 8 FCPATH/index.php(46): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-01-12 18:04:57 --> ErrorException: pg_query(): Query failed: ERROR:  relation &quot;users&quot; does not exist
LINE 2: FROM &quot;users&quot;
             ^ in /var/www/html/system/Database/Postgre/Connection.php:204
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', '/var/www/html/s...', 204)
#1 /var/www/html/system/Database/Postgre/Connection.php(204): pg_query(Object(PgSql\Connection), 'SELECT *\nFROM "...')
#2 /var/www/html/system/Database/BaseConnection.php(734): CodeIgniter\Database\Postgre\Connection->execute('SELECT *\nFROM "...')
#3 /var/www/html/system/Database/BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM "...')
#4 /var/www/html/system/Database/BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM "...', Array, false)
#5 /var/www/html/system/Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#6 /var/www/html/system/BaseModel.php(610): CodeIgniter\Model->doFind(true, 'D20211097851')
#7 /var/www/html/app/Controllers/AuthController.php(26): CodeIgniter\BaseModel->find('D20211097851')
#8 /var/www/html/system/CodeIgniter.php(933): App\Controllers\AuthController->login()
#9 /var/www/html/system/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
#10 /var/www/html/system/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 /var/www/html/system/Boot.php(325): CodeIgniter\CodeIgniter->run()
#12 /var/www/html/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 /var/www/html/public/index.php(46): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}
CRITICAL - 2025-01-12 18:04:57 --> Error: Call to a member function getFirstRow() on bool
[Method: POST, Route: login]
in SYSTEMPATH/Model.php on line 211.
 1 SYSTEMPATH/BaseModel.php(610): CodeIgniter\Model->doFind(true, 'D20211097851')
 2 APPPATH/Controllers/AuthController.php(26): CodeIgniter\BaseModel->find('D20211097851')
 3 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\AuthController->login()
 4 SYSTEMPATH/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
 5 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 SYSTEMPATH/Boot.php(325): CodeIgniter\CodeIgniter->run()
 7 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 8 FCPATH/index.php(46): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-01-12 18:18:45 --> ErrorException: pg_query(): Query failed: ERROR:  relation &quot;users&quot; does not exist
LINE 2: FROM &quot;users&quot;
             ^ in /var/www/html/system/Database/Postgre/Connection.php:204
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', '/var/www/html/s...', 204)
#1 /var/www/html/system/Database/Postgre/Connection.php(204): pg_query(Object(PgSql\Connection), 'SELECT *\nFROM "...')
#2 /var/www/html/system/Database/BaseConnection.php(734): CodeIgniter\Database\Postgre\Connection->execute('SELECT *\nFROM "...')
#3 /var/www/html/system/Database/BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM "...')
#4 /var/www/html/system/Database/BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM "...', Array, false)
#5 /var/www/html/system/Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#6 /var/www/html/system/BaseModel.php(610): CodeIgniter\Model->doFind(true, 'D20211097851')
#7 /var/www/html/app/Controllers/AuthController.php(26): CodeIgniter\BaseModel->find('D20211097851')
#8 /var/www/html/system/CodeIgniter.php(933): App\Controllers\AuthController->login()
#9 /var/www/html/system/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
#10 /var/www/html/system/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 /var/www/html/system/Boot.php(325): CodeIgniter\CodeIgniter->run()
#12 /var/www/html/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 /var/www/html/public/index.php(46): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}
CRITICAL - 2025-01-12 18:18:46 --> Error: Call to a member function getFirstRow() on bool
[Method: POST, Route: login]
in SYSTEMPATH/Model.php on line 211.
 1 SYSTEMPATH/BaseModel.php(610): CodeIgniter\Model->doFind(true, 'D20211097851')
 2 APPPATH/Controllers/AuthController.php(26): CodeIgniter\BaseModel->find('D20211097851')
 3 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\AuthController->login()
 4 SYSTEMPATH/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
 5 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 SYSTEMPATH/Boot.php(325): CodeIgniter\CodeIgniter->run()
 7 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 8 FCPATH/index.php(46): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-01-12 18:29:29 --> Error connecting to the database: ErrorException: pg_connect(): Unable to connect to PostgreSQL server: connection to server at &quot;localhost&quot; (::1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at &quot;localhost&quot; (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections? in /var/www/html/system/Database/Postgre/Connection.php:77
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_connect(): U...', '/var/www/html/s...', 77)
#1 /var/www/html/system/Database/Postgre/Connection.php(77): pg_connect('host=localhost ...')
#2 /var/www/html/system/Database/BaseConnection.php(421): CodeIgniter\Database\Postgre\Connection->connect(false)
#3 /var/www/html/system/Database/BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
#4 /var/www/html/system/Database/BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM "...', Array, false)
#5 /var/www/html/system/Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#6 /var/www/html/system/BaseModel.php(610): CodeIgniter\Model->doFind(true, 'D20211097851')
#7 /var/www/html/app/Controllers/AuthController.php(26): CodeIgniter\BaseModel->find('D20211097851')
#8 /var/www/html/system/CodeIgniter.php(933): App\Controllers\AuthController->login()
#9 /var/www/html/system/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
#10 /var/www/html/system/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 /var/www/html/system/Boot.php(325): CodeIgniter\CodeIgniter->run()
#12 /var/www/html/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 /var/www/html/public/index.php(46): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}
CRITICAL - 2025-01-12 18:29:29 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [Postgre]: pg_connect(): Unable to connect to PostgreSQL server: connection to server at &quot;localhost&quot; (::1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at &quot;localhost&quot; (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
[Method: POST, Route: login]
in SYSTEMPATH/Database/BaseConnection.php on line 467.
 1 SYSTEMPATH/Database/BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH/Database/BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM "users"
WHERE "users"."student_id" = :users.student_id:', [...], false)
 3 SYSTEMPATH/Model.php(210): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH/BaseModel.php(610): CodeIgniter\Model->doFind(true, 'D20211097851')
 5 APPPATH/Controllers/AuthController.php(26): CodeIgniter\BaseModel->find('D20211097851')
 6 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\AuthController->login()
 7 SYSTEMPATH/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
 8 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH/Boot.php(325): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH/index.php(46): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-01-12 18:30:29 --> ErrorException: pg_query(): Query failed: ERROR:  relation &quot;users&quot; does not exist
LINE 2: FROM &quot;users&quot;
             ^ in /var/www/html/system/Database/Postgre/Connection.php:204
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', '/var/www/html/s...', 204)
#1 /var/www/html/system/Database/Postgre/Connection.php(204): pg_query(Object(PgSql\Connection), 'SELECT *\nFROM "...')
#2 /var/www/html/system/Database/BaseConnection.php(734): CodeIgniter\Database\Postgre\Connection->execute('SELECT *\nFROM "...')
#3 /var/www/html/system/Database/BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM "...')
#4 /var/www/html/system/Database/BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM "...', Array, false)
#5 /var/www/html/system/Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#6 /var/www/html/system/BaseModel.php(610): CodeIgniter\Model->doFind(true, 'D20211097851')
#7 /var/www/html/app/Controllers/AuthController.php(26): CodeIgniter\BaseModel->find('D20211097851')
#8 /var/www/html/system/CodeIgniter.php(933): App\Controllers\AuthController->login()
#9 /var/www/html/system/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
#10 /var/www/html/system/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 /var/www/html/system/Boot.php(325): CodeIgniter\CodeIgniter->run()
#12 /var/www/html/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 /var/www/html/public/index.php(46): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}
CRITICAL - 2025-01-12 18:30:29 --> Error: Call to a member function getFirstRow() on bool
[Method: POST, Route: login]
in SYSTEMPATH/Model.php on line 211.
 1 SYSTEMPATH/BaseModel.php(610): CodeIgniter\Model->doFind(true, 'D20211097851')
 2 APPPATH/Controllers/AuthController.php(26): CodeIgniter\BaseModel->find('D20211097851')
 3 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\AuthController->login()
 4 SYSTEMPATH/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
 5 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 SYSTEMPATH/Boot.php(325): CodeIgniter\CodeIgniter->run()
 7 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 8 FCPATH/index.php(46): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-01-12 18:36:57 --> ErrorException: pg_query(): Query failed: ERROR:  relation &quot;student_subjects&quot; does not exist
LINE 2: FROM &quot;student_subjects&quot;
             ^ in /var/www/html/system/Database/Postgre/Connection.php:204
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', '/var/www/html/s...', 204)
#1 /var/www/html/system/Database/Postgre/Connection.php(204): pg_query(Object(PgSql\Connection), 'SELECT *\nFROM "...')
#2 /var/www/html/system/Database/BaseConnection.php(734): CodeIgniter\Database\Postgre\Connection->execute('SELECT *\nFROM "...')
#3 /var/www/html/system/Database/BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM "...')
#4 /var/www/html/system/Database/BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM "...', Array, false)
#5 /var/www/html/system/Model.php(286): CodeIgniter\Database\BaseBuilder->get()
#6 /var/www/html/system/BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
#7 /var/www/html/app/Controllers/StudentSubjectsController.php(139): CodeIgniter\BaseModel->findAll()
#8 /var/www/html/system/CodeIgniter.php(933): App\Controllers\StudentSubjectsController->skill()
#9 /var/www/html/system/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\StudentSubjectsController))
#10 /var/www/html/system/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 /var/www/html/system/Boot.php(325): CodeIgniter\CodeIgniter->run()
#12 /var/www/html/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 /var/www/html/public/index.php(46): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}
CRITICAL - 2025-01-12 18:36:57 --> Error: Call to a member function getResult() on bool
[Method: GET, Route: skills]
in SYSTEMPATH/Model.php on line 287.
 1 SYSTEMPATH/BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
 2 APPPATH/Controllers/StudentSubjectsController.php(139): CodeIgniter\BaseModel->findAll()
 3 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\StudentSubjectsController->skill()
 4 SYSTEMPATH/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\StudentSubjectsController))
 5 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 SYSTEMPATH/Boot.php(325): CodeIgniter\CodeIgniter->run()
 7 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 8 FCPATH/index.php(46): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
